### ISSUE TITLE
Please add an RSS or Atom feed

### ISSUE THREAD

**Issue by Minoru** [meribold/meribold.org#1]
Hi! Got an interesting blog here, keep it up!

RSS and Atom allow readers of your blog to subscribe to updates. This way readers don't have to constantly check your site for new articles. I'm not using Jekyll myself, but it looks like there's [a ready-made gem](https://github.com/jekyll/jekyll-feed) that will automate everything for you.

**Comment by meribold** [comment]
There is a feed with a lonely article now: <https://meribold.github.io/feed.xml>.

I hadn't used a feed reader before and spend some time familiarizing myself with that first.  I ended up using Newsbeuter/Newsboat.  It's aweome—thank you for maintaining Newsbeuter and now Newsboat!

Let me know if there are any issues with my feed.
